export const shareInfo = {
  title: "迈出回家第一步，雷凌双擎伙力接送免单活动",
  desc: "管家APP购买春运回家票，雷凌双擎伙力接送免费乘",
  link: `${window.location.origin}/fe/app/client/mall/html/active-page/active/20161215.html`,
  img: "http://cdn.rsscc.cn/guanggao/img/mall/active/leiling/leiling-share.png"
};
let imgBase = "http://cdn.rsscc.cn/guanggao/img/mall/active/leiling/";
// 预加载图片列表
export const imgList = [
  // 人物
  `${imgBase}active-2-1-1.jpg?v=1.0`,
  `${imgBase}active-2-1-2.jpg?v=1.0`,
  `${imgBase}active-2-1-3.jpg?v=1.0`,
  `${imgBase}active-2-2-1.jpg?v=1.0`,
  `${imgBase}active-2-2-2.jpg?v=1.0`,
  `${imgBase}active-2-2-3.jpg?v=1.0`,
  `${imgBase}active-2-3-1.jpg?v=1.0`,
  `${imgBase}active-2-3-2.jpg?v=1.0`,
  `${imgBase}active-2-3-3.jpg?v=1.0`,
  `${imgBase}active-2-4-1.jpg?v=1.0`,
  `${imgBase}active-2-4-2.jpg?v=1.0`,
  `${imgBase}active-2-4-3.jpg?v=1.0`,
  `${imgBase}active-2-5-1.jpg?v=1.0`,

  `${imgBase}active-2-2.png?v=1.0`,
  `${imgBase}active-3-2.png?v=1.0`,
  `${imgBase}active-3-3.png?v=1.0`,
  `${imgBase}active-3-4.png?v=1.0`,
  `${imgBase}active-3-5.png?v=1.0`,
  `${imgBase}active-3-6.png?v=1.0`,
  `${imgBase}active-4-2.png?v=1.0`,
  `${imgBase}active-4-3.png?v=1.0`,
  `${imgBase}active-4-4.png?v=1.0`,
  `${imgBase}active-4-5.png?v=1.0`,
  `${imgBase}active-4-6.png?v=1.0`,
  `${imgBase}active-5-2.png?v=1.0`,
  `${imgBase}active-5-3.png?v=1.0`,
  `${imgBase}active-5-4.png?v=1.0`,
  `${imgBase}active-5-5.png?v=1.0`,
  `${imgBase}active-5-6.png?v=1.0`,
  `${imgBase}active-5-7.png?v=1.0`,
  `${imgBase}active-6-2.png?v=1.0`,
  `${imgBase}active-6-3.png?v=1.0`,
  `${imgBase}active-6-4.png?v=1.0`,
  `${imgBase}active-6-5.png?v=1.0`,
  `${imgBase}active-6-6.png?v=1.0`,
  `${imgBase}active-7-2.png?v=1.0`,
  `${imgBase}active-7-3.png?v=1.0`,
  `${imgBase}active-7-4.png?v=1.0`,
  `${imgBase}active-7-6.png?v=1.0`,
  `${imgBase}active-7-7.png?v=1.0`,
  `${imgBase}active-8-2.png?v=1.0`,
  `${imgBase}active-8-3.jpg?v=1.0`,
  `${imgBase}active-8-4.jpg?v=1.0`,
  `${imgBase}active-8-5.png?v=1.0`,
  `${imgBase}active-8-6.png?v=1.0`,
  `${imgBase}active-8-8.png?v=1.0`,
  `${imgBase}active-9-3.png?v=1.0`,
];
